server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache assets agressif (Vite génère des noms avec hash)
    location ~* \.(?:js|css|woff2?|svg|ico|png|jpg|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Désactiver le cache sur index.html
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Compression
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
